# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  # Create database server
    config.vm.define "database" do |database|
      database.vm.hostname = "database"
      database.vm.network "private_network", ip: "192.168.22.200"
    end
  
  # Create 3 web servers
  N = 3
  (1..N).each do |m_id|
    config.vm.define "webserver#{m_id}" do |webserver|
      webserver.vm.hostname = "webserver#{m_id}"
      webserver.vm.network "private_network", ip: "192.168.22.#{200+m_id}"
    end
  end
  
  # Create balancer machine, also install Ansible
  config.vm.define "balancer" do |balancer| 
    balancer.vm.hostname = "balancer"
    balancer.vm.network :private_network, ip: "192.168.22.100"
    
    # Copy ssh keys for webservers
    (1..N).each do |webserver_n|
        balancer.vm.provision "file", source: ".vagrant/machines/webserver#{webserver_n}/virtualbox/private_key", destination: "/home/vagrant/machines/webserver#{webserver_n}.private_key"
        balancer.vm.provision "shell", inline: "chmod 0600 /home/vagrant/machines/webserver#{webserver_n}.private_key"
    end

    # Copy ssh keys for database
    balancer.vm.provision "file", source: ".vagrant/machines/database/virtualbox/private_key", destination: "/home/vagrant/machines/database.private_key"
    balancer.vm.provision "shell", inline: "chmod 0600 /home/vagrant/machines/database.private_key"
    
    # Install Ansible and start playbook
    balancer.vm.provision "ansible_local" do |ansible|
      ansible.install        = true
      #ansible.verbose        = true	 
      ansible.playbook       = "ansible/moodle_pb.yml"
      ansible.inventory_path = "ansible/hosts"
      ansible.limit          = "all"
    end

#    balancer.vm.provision "shell", :inline => "sudo cat /vagrant/ansible/hosts > /etc/ansible/hosts"
  end
  
    # Allow SSH connection without key checking
    config.vm.provision "shell", inline: "sudo sed -i 's/#   StrictHostKeyChecking ask/StrictHostKeyChecking no/g' /etc/ssh/ssh_config"
end