---

- name: Install remi repo
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present
  tags: packages

- name: Enabled php72 repo
  command: yum-config-manager --enable remi-php72
  tags: configuration

- name: Install epel and yum utils
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - epel-release
    - yum-utils
  tags: packages

- name: Install php and php modules
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - php
    - php-zip
    - php-gd
    - php-intl
    - php-mbstring
    - php-soap
    - php-xmlrpc
    - php-opcache
    - php-iconv
    - php-curl
    - php-ctype
    - php-simplexml
    - php-spl
    - php-pgsql
  notify: restart httpd
  tags: packages